# Generated by Django 4.2.5 on 2023-09-30 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(16)])),
                ('category', models.CharField(choices=[(12, 'Action'), (2, 'Comedy'), (18, 'Stand-Up')], max_length=16)),
                ('age', models.CharField(choices=[(2, 'Kids'), (12, 'Young'), (18, 'Adult')], max_length=8)),
            ],
        ),
    ]
