# Generated by Django 4.2.5 on 2023-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.IntegerField(choices=[(2, 'Kids'), (12, 'Young'), (18, 'Adult')], max_length=8),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.IntegerField(choices=[(12, 'Action'), (2, 'Comedy'), (18, 'Stand-Up')], max_length=16),
        ),
    ]
