# Generated by Django 4.2.5 on 2023-10-03 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_movie_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.IntegerField(choices=[(2, 'Kids'), (12, 'Young'), (18, 'Adult')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.IntegerField(choices=[(12, 'Action'), (2, 'Comedy'), (18, 'Stand-Up')]),
        ),
        migrations.CreateModel(
            name='RentedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
