# Generated by Django 4.2.5 on 2023-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_requestedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedmovie',
            name='approved',
            field=models.CharField(choices=[('A', 'Approved'), ('Q', 'Queue'), ('D', 'Declined')], default='Q', max_length=16),
        ),
    ]
