# Generated by Django 4.2.5 on 2023-10-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
