# Generated by Django 4.2.5 on 2023-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedmovie',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rentedmovie',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
