# Generated by Django 4.2.5 on 2023-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rentedmovie_valid_from_rentedmovie_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedmovie',
            name='expired',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
