# Generated by Django 4.2.5 on 2023-10-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_rentedmovie_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentedmovie',
            old_name='expired',
            new_name='expired_movie',
        ),
    ]
