# Generated by Django 4.2.5 on 2023-10-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_expired_rentedmovie_expired_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedmovie',
            name='valid_from',
        ),
    ]
