# Generated by Django 4.2.5 on 2023-10-06 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_rentedmovie_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedmovie',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
